### ISSUE TITLE
Can we make this jruby friendly?

### ISSUE THREAD

**Issue by matthewford** [igrigorik/textquery#4]
By not requiring:

  require 'active_support'
  require 'oniguruma'

And not calling .mb_chars?

I'm sorry to say my hack for now, to test out this lib was to redefine RUBY_VERSION = 1.9 if jruby.

**Comment by igrigorik** [comment]
Hmm, the mb_chars is a bit of a mess, but if you do run JRuby under 1.9 mode, everything works as expected: 

(M=ef500e) igrigorik /git/textquery> ruby --1.9 spec/textquery_spec.rb 
/Users/igrigorik/Development/github/textquery/lib/textquery/textquery.rb:92 warning: `eval' should not be aliased
........................

Finished in 0.728 seconds
24 examples, 0 failures

(M=ef500e) igrigorik /git/textquery> ruby -v
jruby 1.5.5 (ruby 1.8.7 patchlevel 249) (2010-11-10 4bd4200) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_22) [x86_64-java]

Problem is, unless you're using active_support's mb_chars on 1.8.7, you'll clobber any matching on unicode text.

**Comment by igrigorik** [comment]
Closing.
